# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Activity.destroy_all
Country.destroy_all

@germany = Country.create!(name: "Germany", pictureurl: "<a title='Rob984 / CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0)' href='https://commons.wikimedia.org/wiki/File:EU-Germany_(orthographic_projection).svg'><img width='215' alt='EU-Germany (orthographic projection)' src='https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/EU-Germany_%28orthographic_projection%29.svg/512px-EU-Germany_%28orthographic_projection%29.svg.png'></a>")
@denmark = Country.create!(name: "Denmark", pictureurl: "<a title='Orionist / CC BY-SA (https://creativecommons.org/licenses/by-sa/3.0)' href='https://commons.wikimedia.org/wiki/File:Kingdom_of_Denmark_(orthographic_projection).svg'><img width='215' alt='Kingdom of Denmark (orthographic projection)' src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Kingdom_of_Denmark_%28orthographic_projection%29.svg/512px-Kingdom_of_Denmark_%28orthographic_projection%29.svg.png'></a>")
@denmark.activities.create!(name: "Tivoli Gardens", description: "Amusement park and pleasure garden in Copenhagen. The park opened on 15 August 1843 and is the second-oldest operating amusement park in the world, after Dyrehavsbakken in nearby Klampenborg, also in Denmark", pictureurl: "<a title='Jorge Láscar from Melbourne, Australia / CC BY (https://creativecommons.org/licenses/by/2.0)' href='https://commons.wikimedia.org/wiki/File:Tivoli_Gardens_(37866889102).jpg'><img width='256' alt='Tivoli Gardens (37866889102)' src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Tivoli_Gardens_%2837866889102%29.jpg/512px-Tivoli_Gardens_%2837866889102%29.jpg'></a>")
@denmark.activities.create!(name: "Kronborg", description: "Castle and stronghold in the town of Helsingør, Denmark. Immortalized as Elsinore in William Shakespeare's play Hamlet, Kronborg is one of the most important Renaissance castles in Northern Europe and has been added to UNESCO's World Heritage Sites list", pictureurl: "<a title='Artico2 / CC BY-SA (https://creativecommons.org/licenses/by-sa/3.0)' href='https://commons.wikimedia.org/wiki/File:Kronborg_002.JPG'><img width='256' alt='Kronborg 002' src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Kronborg_002.JPG/256px-Kronborg_002.JPG'></a>")

@switzerland = Country.create!(name: "Switzerland", pictureurl: "<a title='TUBS / CC BY-SA (https://creativecommons.org/licenses/by-sa/3.0)' href='https://commons.wikimedia.org/wiki/File:Switzerland_on_the_globe_(Europe_centered).svg'><img width='215' alt='Switzerland on the globe (Europe centered)' src='https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Switzerland_on_the_globe_%28Europe_centered%29.svg/512px-Switzerland_on_the_globe_%28Europe_centered%29.svg.png'></a>")
@switzerland.activities.create!(name: "Harder Kulm", description: "The Harderkulm is a viewpoint at 1,321 metres in the Berner Oberland region of Switzerland, overlooking the towns of Interlaken and Unterseen", pictureurl: "<a title='Wikieditkid / CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0)' href='https://commons.wikimedia.org/wiki/File:View_from_Harder_Kulm.jpg'><img width='256' alt='View from Harder Kulm' src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/View_from_Harder_Kulm.jpg/256px-View_from_Harder_Kulm.jpg'></a>")
@switzerland.activities.create!(name: "Oeschinen Lake", description: "Oeschinen Lake is a lake in the Bernese Oberland, Switzerland, 4 kilometres east of Kandersteg in the Oeschinen valley", pictureurl: "<a title='Roland Zumbühl (Picswiss), Arlesheim (Commons:Picswiss project) / CC BY-SA (http://creativecommons.org/licenses/by-sa/3.0/)' href='https://commons.wikimedia.org/wiki/File:Oeschinensee.jpg'><img width='256' alt='Oeschinensee' src='https://upload.wikimedia.org/wikipedia/commons/d/d5/Oeschinensee.jpg'></a>")
@switzerland.activities.create!(name: "Staubbach Falls", description: "The Staubbach Fall is a waterfall in Switzerland, located just west above Lauterbrunnen in the Bernese Highlands. The waterfall drops 297 metres from a hanging valley that ends in overhanging cliffs above the Weisse Lütschine", pictureurl: "<a title='Andrew Bossi / CC BY-SA (https://creativecommons.org/licenses/by-sa/2.5)' href='https://commons.wikimedia.org/wiki/File:5320_-_Lauterbrunnen_-_Staubbachf%C3%A4lle_viewed_from_Wegneralpbahn.JPG'><img width='256' alt='5320 - Lauterbrunnen - Staubbachfälle viewed from Wegneralpbahn' src='https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/5320_-_Lauterbrunnen_-_Staubbachf%C3%A4lle_viewed_from_Wegneralpbahn.JPG/256px-5320_-_Lauterbrunnen_-_Staubbachf%C3%A4lle_viewed_from_Wegneralpbahn.JPG'></a>")
@switzerland.activities.create!(name: "Schynige Platte", description: "The Schynige Platte is a small mountain ridge and a viewpoint in the Bernese Highlands and belongs to the Schwarzhorn group.", pictureurl: "<a title='Andrew Bossi / CC BY-SA (https://creativecommons.org/licenses/by-sa/2.5)' href='https://commons.wikimedia.org/wiki/File:5843_-_Schynige_Platte_-_Interlaken,_Thunersee,_Abendberg,_and_Morgenberghorn_viewed_from_Oberberghorn.JPG'><img width='256' alt='5843 - Schynige Platte - Interlaken, Thunersee, Abendberg, and Morgenberghorn viewed from Oberberghorn' src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/5843_-_Schynige_Platte_-_Interlaken%2C_Thunersee%2C_Abendberg%2C_and_Morgenberghorn_viewed_from_Oberberghorn.JPG/256px-5843_-_Schynige_Platte_-_Interlaken%2C_Thunersee%2C_Abendberg%2C_and_Morgenberghorn_viewed_from_Oberberghorn.JPG'></a>")
@switzerland.activities.create!(name: "Rochers de Naye", description: "The Rochers de Naye are mountains of the Swiss Alps, overlooking Lake Geneva near Montreux and Villeneuve, in the canton of Vaud. They lie on the range separating the basin of Lake Geneva from the valley of the Sarine, on the watershed between the Rhone and the Rhine", pictureurl: "<a title='Zacharie Grossen / CC BY-SA (https://creativecommons.org/licenses/by-sa/4.0)' href='https://commons.wikimedia.org/wiki/File:Rochers_de_Naye_E.jpg'><img width='256' alt='Rochers de Naye E' src='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Rochers_de_Naye_E.jpg/256px-Rochers_de_Naye_E.jpg'></a>")
@switzerland.activities.create!(name: "Zytglogge", description: "The Zytglogge is a landmark medieval tower in Bern, Switzerland. Built in the early 13th century, it has served the city as guard tower, prison, clock tower, centre of urban life and civic memorial", pictureurl: "<a title='Sergey Ashmarin / CC BY-SA (https://creativecommons.org/licenses/by-sa/3.0)' href='https://commons.wikimedia.org/wiki/File:Zytglogge_Tower_-_Bern,_Switzerland_-_panoramio.jpg'><img width='256' alt='Zytglogge Tower - Bern, Switzerland - panoramio' src='https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Zytglogge_Tower_-_Bern%2C_Switzerland_-_panoramio.jpg/256px-Zytglogge_Tower_-_Bern%2C_Switzerland_-_panoramio.jpg'></a>")
